apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bjw-s.yaml
  - calico.yaml
  - coredns.yaml
  - external-dns.yaml
  - harbor.yaml
  - jetstack.yaml
  - metrics-server.yaml
  - stakater.yaml
