---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-homelab-dns
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/homelab-dns/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: homelab-dns
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 3m
