---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  PROVISION_DIR: "{{.ROOT_DIR}}/provision"
  ANSIBLE_DIR: "{{.ROOT_DIR}}/provision/ansible"

dotenv: [".config.env"]

env:
  KUBECONFIG: "{{.ROOT_DIR}}/provision/kubeconfig"
  SOPS_AGE_KEY_FILE: ~/.config/sops/age/keys.txt

includes:
  ansible: .taskfiles/Ansible/Tasks.yml
  cluster: .taskfiles/Cluster/Tasks.yml
  debug: .taskfiles/Debug/Tasks.yml
  fx: .taskfiles/Flux/Tasks.yml
  ku: .taskfiles/Kubernetes/Tasks.yml

tasks:

  default:
    silent: true
    cmd: task -l
