---
# yaml-language-server: $schema=https://kubernetes-schemas.haraldkoch.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: 1.13.0
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    expose:
      type: loadBalancer
      tls:
        certSource: secret
        secret:
          secretName: tls.harbor
      loadBalancer:
        name: harbor
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "harbor.${SECRET_DOMAIN}"
    externalURL: https://harbor.${SECRET_DOMAIN}
    ipFamily:
      ipv6:
        enabled: false
    persistence:
      enabled: true
      persistentVolumeClaim:
        registry:
          existingClaim: harbor-registry-v1
          storageClass: local-path
          subPath: registry
        chartmuseum:
          existingClaim: harbor-registry-v1
          storageClass: local-path
          subPath: chartmuseum
    harborAdminPassword: "${SECRET_HARBOR_ADMIN_PASSWORD}"
    # The secret key used for encryption. Must be a string of 16 chars.
    secretKey: "${SECRET_HARBOR_ENCRPYTION_KEY}"

    notary:
      enabled: false

    nginx:
      podAnnotations:
        secret.reloader.stakater.com/reload: tls.harbor
