---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zot
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/project-zot/zot-linux-amd64
              tag: v1.4.3
            env:
              TZ: ${TIMEZONE}
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /v2/
                    port: 8080
                  initialDelaySeconds: 5
              readiness: *probe
              startup:
                enabled: false
    service:
      main:
        ipFamilyPolicy: PreferDualStack
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
        hosts:
          - host: &host zot.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: configMap
        name: zot-config # overridden by kubeconfig
        globalMounts:
          - path: /etc/zot
      secret:
        type: secret
        name: zot-secret
      registry:
        existingClaim: zot-registry-v1
        globalMounts:
          - path: /var/lib/registry
