---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./registry-pvc.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: zot-config
    files:
      - config.json=./config/config.json
generatorOptions:
  disableNameSuffixHash: true
