---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zot-registry-v1
  namespace: zot
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 50Gi

  storageClassName: local-path
