---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "${SECRET_LETSENCRYPT_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          rfc2136:
            nameserver: "${SECRET_EXTERNAL_DNS_SERVER}"
            tsigKeyName: externaldns
            tsigAlgorithm: HMACSHA256
            tsigSecretSecretRef:
              name: cert-manager-secret
              key: tsig-secret-key
        selector:
          dnsZones:
            - ${SECRET_DOMAIN}
