---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tigera-operator
  namespace: tigera-operator
spec:
  interval: 15m
  chart:
    spec:
      chart: tigera-operator
      version: v3.24.3
      sourceRef:
        kind: HelmRepository
        name: calico
        namespace: flux-system

  install:
    createNamespace: true
    crds: Create
    remediation: # perform remediation when helm install fails
      retries: 5

  upgrade:
    crds: CreateReplace
    remediation: # perform remediation when helm upgrade fails
      retries: 5
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true

  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true

  values:
    # Configures general installation parameters for Calico. Schema is based
    # on the operator.tigera.io/Installation API documented
    # here: https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.InstallationSpec
    installation:
      enabled: true
      # Configures Calico networking.
      calicoNetwork:
        # Note: The ipPools section cannot be modified post-install.
        ipPools:
          - blockSize: 26
            cidr: 10.52.0.0/16
            encapsulation: VXLANCrossSubnet
            natOutgoing: Enabled
            nodeSelector: all()
