---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 15m
  chart:
    spec:
      chart: harbor
      version: 1.10.0
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    expose:
      type: ingress
      tls:
        certSource: none
      ingress:
        className: nginx
        hosts:
          core: harbor.${SECRET_DOMAIN}
        annotations:
          ingress.kubernetes.io/ssl-redirect: "true"
          ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          traefik.ingress.kubernetes.io/buffering: |
            # 2GiB
            maxrequestbodybytes: 2147483648
            # 64MiB
            memrequestbodybytes: 67108864
          nginx.ingress.kubernetes.io/client_max_body_size: "2147483648"
    externalURL: https://harbor.${SECRET_DOMAIN}
    ipFamily:
      ipv6:
        enabled: false
    persistence:
      enabled: true
      persistentVolumeClaim:
        registry:
          existingClaim: harbor-registry-v1
          storageClass: local-path
          subPath: registry
        chartmuseum:
          existingClaim: harbor-registry-v1
          storageClass: local-path
          subPath: chartmuseum
    harborAdminPassword: "${SECRET_HARBOR_ADMIN_PASSWORD}"
    # The secret key used for encryption. Must be a string of 16 chars.
    secretKey: "${SECRET_HARBOR_ENCRPYTION_KEY}"

    notary:
      enabled: false
