apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:fks8uDdHvM7ojoWsB1wp42mSpDO7sb7zv3FZ8AVLgFdKHUKbYo7G5ZBGUdZaCsfskGg47aF92Ew9lh/c,iv:n5perxmiGcJZHF8B4w/bTHmUcgJyWzlqEp+UOozvx2Q=,tag:1BLnT/rzy2NgFVHhK4ZEGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncxmpfzemcs4327v7hw5ea2dxvqypsygad2d3rjarqa5t6l9cqqse9ek5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRC9qVmx1T1UyekQyTkhq
            QVBTRkxLT2xLeXJPTUh6a1NWeE5QbU5CRGxjClljZlo0K0J6Yk9Wd2MxWFY3d052
            cHM2c0dkSXEwTWxSZDdoN3VSbVMvQUEKLS0tIDUyUGwydWRiMnJOaWt6MklYdXVE
            bDlBbTZtSi9NK1hkZU1xRnVxdXVzRzQK3rnh3xaEdIwh7o1O3Uzhg2naRCpst418
            3NrsJQAObqQILRcc9pH1rKFKdC2UVVo+h6Vm6vRtmizx71TsB0M6Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-19T17:45:24Z"
    mac: ENC[AES256_GCM,data:2+HH7VQSnN0vTojhJHOti5mf5bGZ8Q0+O31Sb/gXQ8Ho+Px9oyehO5IMatHlRQ1MFn92zcyGqBa5fpAqsuhFTmpl4XjiywWwlfQp4/fgndsW4MS/lfrjGso/iXHTM9tr5WIKVSOnKlZ+XWX1S4tgHBaGZ5q67zAkhqS/62gDneQ=,iv:09itSVIC1zVUy9XOK6wjqKomHfV6peKC/DFkiaQS+gQ=,tag:vG0sBLex5YRl9TkfBSQJtA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
