apiVersion: v1
kind: Secret
metadata:
    # weave-gitops expects this name
    name: cluster-user-auth
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:louciLI=,iv:ve3v1So2lpvHQkRwv4OtnCEE89pIe6w3tUOXL3FAm7k=,tag:twfvRczx2kcXUzQyR2kfhQ==,type:str]
    password: ENC[AES256_GCM,data:Ru3hSpLmyxsGLUUPjAEDOxWz0KtGfTxD13yAjNgPHw20rfqQ9C+EeH1qbTnW8O5TfD59MJwr4v7DZcpi,iv:v5inRZyUZog2/RVbYHip3HolsdfhHfRNOAVpFOB6Bbk=,tag:bGejBS5EbGuq9IjnUnHjwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncxmpfzemcs4327v7hw5ea2dxvqypsygad2d3rjarqa5t6l9cqqse9ek5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRC9qVmx1T1UyekQyTkhq
            QVBTRkxLT2xLeXJPTUh6a1NWeE5QbU5CRGxjClljZlo0K0J6Yk9Wd2MxWFY3d052
            cHM2c0dkSXEwTWxSZDdoN3VSbVMvQUEKLS0tIDUyUGwydWRiMnJOaWt6MklYdXVE
            bDlBbTZtSi9NK1hkZU1xRnVxdXVzRzQK3rnh3xaEdIwh7o1O3Uzhg2naRCpst418
            3NrsJQAObqQILRcc9pH1rKFKdC2UVVo+h6Vm6vRtmizx71TsB0M6Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T14:25:41Z"
    mac: ENC[AES256_GCM,data:xI8tIalYIKamf/T09YsxRlVX/UIu/IiwcA0e8ASMH2wimTZ3B/Etiw8ZZBR20OvUJLmXuznI9uWAGLMAAOVvOpw3gjrcM10AfsQ9B+dTL5XIkFfMlESPAwDOyTmbHHgCtiGi4SEreJQuAYcGRRE95mHeIKPKwGtJxxwrtF9Eojs=,iv:y+BYaHTyZleDWlR+EkdI786BaLSrm0jOTpEgzkO7tZ0=,tag:pkD6kaTncV9Gh7ZgBr/rzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
