---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: coredns
      version: 1.19.7
      sourceRef:
        kind: HelmRepository
        name: coredns
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:
    image:
      repository: coredns/coredns
      tag: 1.10.1

    fullnameOverride: coredns

    replicaCount: 2

    service:
      clusterIP: 10.53.0.10
      annotations:
        fix.coredns.template: "fnord"

    serviceAccount:
      create: true

    prometheus:
      service:
        enabled: true

    podAnnotations:
      configmap.reloader.stakater.com/reload: "coredns"

    servers:
      - zones:
          - zone: .
            scheme: dns://
            use_tcp: true
        port: 53
        plugins:
          - name: log
          - name: errors
          - name: health
            configBlock: |-
              lameduck 5s
          - name: ready
          - name: kubernetes
            parameters: cluster.local in-addr.arpa ip6.arpa
            configBlock: |-
              pods insecure
              fallthrough in-addr.arpa ip6.arpa
              ttl 30
          # - name: hosts
          #   parameters: /etc/coredns/NodeHosts
          #   configBlock: |-
          #     ttl 60
          #     reload 15s
          #     fallthrough
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: forward
            parameters: . /etc/resolv.conf
          - name: cache
            parameters: 30
          - name: loop
          - name: reload
          - name: loadbalance

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists

    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
      - key: node-role.kubernetes.io/master
        operator: Exists
