---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Toronto"
  KUBE_VIP_ADDR: "192.168.20.66"
  METALLB_LB_RANGE: "192.168.20.67-192.168.20.68"
  METALLB_K8S_GATEWAY_ADDR: "192.168.20.67"
  METALLB_INGRESS_ADDR: "192.168.20.68"

  NETWORK_K8S_HOST_CIDR: 192.168.20.0/24
  NETWORK_K8S_POD_CIDR: 10.42.0.0/16
  NETWORK_K8S_SERVICE_CIDR: 10.43.0.0/16
