---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Toronto"
  KUBE_VIP_ADDR: "192.168.20.66"
  METALLB_LB_RANGE: "192.168.20.67-192.168.20.68"
  METALLB_K8S_GATEWAY_ADDR: "192.168.20.67"
  METALLB_INGRESS_ADDR: "192.168.20.68"
