apiVersion: v1
kind: Secret
metadata:
    name: internal-dns
    namespace: networking
    labels:
        app.kubernetes.io/name: internal-dns
        app.kubernetes.io/instance: internal-dns
type: Opaque
data:
    rfc2136_tsig_secret: ENC[AES256_GCM,data:L2GlXbCMrErZ8yDZtQaEC8vFnmYVatFS4ZNEMsMMu/46LheBfCBk3Xo+qYJJ1vHdny8DhB8/2NpTNXF3,iv:up6/fIwOvRla0qMCMJxz5IB/xDqbn6yUjceyK9bYdjU=,tag:fB8po7hjJmJY8zqL6KE5kA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncxmpfzemcs4327v7hw5ea2dxvqypsygad2d3rjarqa5t6l9cqqse9ek5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTGxMSWFOTzM1SXY1Z1M5
            RmhRdmVWYjl1bjJWajFseVg3RDVGNk16blhRClh4VXJ6KzM0b2Iyb2JzK3NGZjlG
            V2lhMWtWWDZ2emI1NERSenc0TG5ZZVUKLS0tIE84VFErUVNVRHRqU285NWY0dEdM
            UkFpc1RBdjNYYVA2emtFbWtub25CaHMK895MhJWaTluSJ0Ckt/hkEkataPzXv8jy
            1YB2Gnp4WCnCvbULocDi0Wx8e5eGmVRvib2Kfo0FZ188BrSlr11tdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-31T18:19:34Z"
    mac: ENC[AES256_GCM,data:ED5cQTMqX9zm9JnNZ03WSZxXn9Q+BSrNiqP1z4+m5/KfcDi+VmL+Npoc9KDz7Ob5rVfOOfbh0o5scghhYOhbpWbchcz8sHQScDgBTFzmDP+O8335KXUuMpBII/R7MtEmlW/l53jFNBPOjeNV6027/atcbq4kY0rrgjDwiJaF8yQ=,iv:xW9/Ela5TLZTA3LUP2oXFEOXecXkGhjqC2QOFqMRwzo=,tag:EMkwx7T9wUJ3m2YnE4jB/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
