---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-pg-backup-nfs
spec:
  storageClassName: harbor-pg-backup-nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_BACKUP_SERVER}
    path: /backup/data/k8s/harbor
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-pg-backup-v1
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: harbor-pg-backup-nfs
