---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: harbor-pgdump
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: cronjob
        cronjob:
          concurrencyPolicy: Forbid
          schedule: "59 * * * *"
        containers:
          main:
            image:
              repository: docker.io/goharbor/harbor-db
              tag: v2.9.1
            command: ["/usr/bin/pg_dumpall"]
            args:
              - "-f"
              - "/backup/harbor.pgdump"
              - "-v"
              - "-U"
              - "postgres"
            env:
              - { name: TZ, value: "${TIMEZONE}" }
              - { name: PGHOST, value: harbor-database }
              - { name: PGPORT, value: "5432" }
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: harbor-database
                    key: POSTGRES_PASSWORD
    persistence:
      backup:
        enabled: true
        type: nfs
        server: ${SECRET_BACKUP_SERVER}
        path: /backup/data/k8s/harbor
    service:
      main:
        enabled: false
