---
# yaml-language-server: $schema=https://kubernetes-schemas.haraldkoch.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor-pgdump
  namespace: harbor
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: cronjob
      cronjob:
        concurrencyPolicy: Forbid
        schedule: "59 * * * *"
    restartPolicy: Never
    image:
      repository: docker.io/goharbor/harbor-db
      tag: v2.8.4
    command: ["/usr/bin/pg_dumpall"]
    args:
      - "-f"
      - "/backup/harbor.pgdump"
      - "-v"
      - "-U"
      - "postgres"
    env:
      - { name: TZ, value: "${TIMEZONE}" }
      - { name: PGHOST, value: harbor-database }
      - { name: PGPORT, value: "5432" }
      - name: PGPASSWORD
        valueFrom:
          secretKeyRef:
            name: harbor-database
            key: POSTGRES_PASSWORD
    service:
      main:
        enabled: false
    persistence:
      backup:
        enabled: true
        type: nfs
        server: ${SECRET_BACKUP_SERVER}
        path: /backup/data/k8s/harbor
        mountPath: /backup
