---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor-pgdump
  namespace: harbor
spec:
  interval: 15m
  chart:
    spec:
      chart: raw
      version: v0.3.1
      sourceRef:
        kind: HelmRepository
        name: dysnix
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    resources:
      - apiVersion: batch/v1
        kind: CronJob
        metadata:
          name: harbor-pgdump
        spec:
          schedule: "59 * * * *"
          concurrencyPolicy: Forbid
          failedJobsHistoryLimit: 5
          successfulJobsHistoryLimit: 3
          jobTemplate:
            spec:
              backoffLimit: 0
              template:
                spec:
                  restartPolicy: Never
                  volumes:
                    - name: backup
                      persistentVolumeClaim:
                        claimName: harbor-pg-backup-v1
                  containers:
                    - name: dump
                      # same image as the postgres cluster
                      image: goharbor/harbor-db:v2.8.2
                      command: ["/usr/bin/pg_dumpall"]
                      args:
                        - "-f"
                        - "/backup/harbor.pgdump"
                        - "-v"
                        - "-U"
                        - "postgres"
                      env:
                        - name: PGHOST
                          value: harbor-database
                        - name: PGPORT
                          value: "5432"
                        - name: PGPASSWORD
                          valueFrom:
                            secretKeyRef:
                              name: harbor-database
                              key: POSTGRES_PASSWORD
                        - name: TZ
                          value: ${TIMEZONE}
                      volumeMounts:
                        - name: backup
                          mountPath: /backup
                      resources:
                        requests:
                          memory: "128Mi"
                          cpu: "1"
                        limits:
                          memory: "512Mi"
                          cpu: "1"
