---
# yaml-language-server: $schema=https://kubernetes-schemas.haraldkoch.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tigera-operator
  namespace: tigera-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: tigera-operator
      version: v3.26.2
      sourceRef:
        kind: HelmRepository
        name: calico
        namespace: flux-system
  maxHistory: 2
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # Configures general installation parameters for Calico. Schema is based
    # on the operator.tigera.io/Installation API documented
    # here: https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.InstallationSpec
    installation:
      enabled: true
      registry: quay.io
      imagePath: calico
      calicoNetwork:
        bgp: Enabled
        hostPorts: Disabled
        # Note: The ipPools section cannot be modified post-install.
        ipPools:
          - blockSize: 26
            cidr: ${NETWORK_K8S_POD_CIDR}
            encapsulation: None
            natOutgoing: Enabled
            nodeSelector: all()
        nodeAddressAutodetectionV4:
          cidrs:
            - ${NETWORK_K8S_HOST_CIDR}
      nodeMetricsPort: 9091
      typhaMetricsPort: 9093
    resources:
      requests:
        cpu: 15m
        memory: 164M
      limits:
        cpu: 500m
        memory: 196M
