apiVersion: v1
kind: Secret
metadata:
    name: homelab-dns
type: Opaque
data:
    rfc2136_tsig_secret: ENC[AES256_GCM,data:m142AAvgHMjZP8mHwXbjqkN7yxZtvbrOTb+Du79HKw5dS6C3NWHp1X+wEKL5z7tTd/+S4acQvttBCxDA,iv:7+cw6MUQ1ehuFAyPN/NROsygai1j1VhnsGagrGjp2+o=,tag:+Sgo/+vX9kp8TreSxQUk0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncxmpfzemcs4327v7hw5ea2dxvqypsygad2d3rjarqa5t6l9cqqse9ek5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWXdPQyt0UEpGdDhoTUh5
            R1VyRWFVRThXTXg0eUozUmNMRk9tZXp6NWk0CkVoLzVWekhzZ1BNS1laa3VPdjlp
            L3hoZWdhejFOalBmYWNTOTY1blRKRW8KLS0tIEttN1c1TnEzSHRtcE01NUJ1NWlo
            cDFsZlVsY2M5SGtMZFVFNjM3VjNZUU0KLAD/kenbTpExg+UJk9PMiwnQ6bvJnVId
            2dWYrV4y43ySvjxE21oxvbHaFbRhIVRSEawWnhKNpfe8se5rKYsCZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T17:09:03Z"
    mac: ENC[AES256_GCM,data:T71V2SZTIHChr298WgqFuzbJ8DVkMKsQQcq+9y0FmCDE2ySMB97oo4JWdSejHyBGBkhGEmHa3cXu4wVhpoEeIxIxsHPM6fhjzD9b95cHdrT8Z/lIuGtt0U63FrmqhFc2v5CoW6sY8iJWRS4+B0LXpCmiwgz3R+wUYZbIdfHHzjk=,iv:2i4g+c+czaXf7RG8bQJ5Q1iNjRM1z5CRVBkq2StscHI=,tag:UKPv7C4AJXfkiIrzwgTt+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
