---
name: "Kubeconform"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["kubernetes/**"]
  pull_request:
    branches: ["main"]
    paths: ["kubernetes/**"]

env:
  KUBERNETES_DIR: ./kubernetes
  SCHEMA_DIR: /home/runner/.datree/crdSchemas

jobs:
  kubeconform:
    name: Kubeconform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup Tools
        run: |
          brew install fluxcd/tap/flux kubeconform kustomize

      - name: Download CRDs
        run: |
          mkdir -p ${{ env.SCHEMA_DIR }}
          flux pull artifact oci://ghcr.io/onedr0p/cluster-crds-oci:latest \
              --output=${{ env.SCHEMA_DIR }}

      - name: Run kubeconform
        run: |
          bash ./.github/scripts/kubeconform.sh ${{ env.KUBERNETES_DIR }} ${{ env.SCHEMA_DIR }}
